title: Chris Craigen
description: Musician, Composer, Performer
baseurl: "" # Leave blank for GitHub Pages
url: "https://jamiepearson.github.io/chris-craigen-website/" # Replace with your GitHub Pages URL
theme: minima
