schema:
  collections:
    - name: pages
      label: Pages
      path: "index.html" # Root directory
      format: html
      fields:
        - name: title
          label: Title
          type: string
        - name: body
          label: Body
          type: string # Use string for HTML content
